// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJa0OimjMiuxlg3Nt6r_E_RjN9KgET4nw',
    appId: '1:618518853469:web:312b973fe8e4b638485ab4',
    messagingSenderId: '618518853469',
    projectId: 'where-s-d-class',
    authDomain: 'where-s-d-class.firebaseapp.com',
    storageBucket: 'where-s-d-class.firebasestorage.app',
    measurementId: 'G-C87PP3XMCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJa0OimjMiuxlg3Nt6r_E_RjN9KgET4nw',
    appId: '1:618518853469:android:placeholder',
    messagingSenderId: '618518853469',
    projectId: 'where-s-d-class',
    storageBucket: 'where-s-d-class.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJa0OimjMiuxlg3Nt6r_E_RjN9KgET4nw',
    appId: '1:618518853469:ios:placeholder',
    messagingSenderId: '618518853469',
    projectId: 'where-s-d-class',
    storageBucket: 'where-s-d-class.firebasestorage.app',
    iosBundleId: 'com.example.whcProto',
  );
}
